// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFAv9_0k-BJuE1v-mnITD2dvKWZRmbszU',
    appId: '1:887208119857:web:ae9a227e75a8d8ed134f10',
    messagingSenderId: '887208119857',
    projectId: 'umai-app',
    authDomain: 'umai-app.firebaseapp.com',
    storageBucket: 'umai-app.appspot.com',
    measurementId: 'G-79NHY4YZE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgSNG26g8urbrpNR21YYo37J-_DKFtFWM',
    appId: '1:887208119857:android:8bdc43ac28c7dd04134f10',
    messagingSenderId: '887208119857',
    projectId: 'umai-app',
    storageBucket: 'umai-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqU_alZEhupVzzN95FIHlqFnkurBloAI',
    appId: '1:887208119857:ios:dfcdefa9fcd7713b134f10',
    messagingSenderId: '887208119857',
    projectId: 'umai-app',
    storageBucket: 'umai-app.appspot.com',
    androidClientId: '887208119857-66iahahhjh9ocg9h3n2q5ljuinb40fh2.apps.googleusercontent.com',
    iosClientId: '887208119857-5fv0csi5q630qh2ajgkdl60ni9sscfhf.apps.googleusercontent.com',
    iosBundleId: 'caelis.studio.umai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqU_alZEhupVzzN95FIHlqFnkurBloAI',
    appId: '1:887208119857:ios:dfcdefa9fcd7713b134f10',
    messagingSenderId: '887208119857',
    projectId: 'umai-app',
    storageBucket: 'umai-app.appspot.com',
    androidClientId: '887208119857-66iahahhjh9ocg9h3n2q5ljuinb40fh2.apps.googleusercontent.com',
    iosClientId: '887208119857-5fv0csi5q630qh2ajgkdl60ni9sscfhf.apps.googleusercontent.com',
    iosBundleId: 'caelis.studio.umai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFAv9_0k-BJuE1v-mnITD2dvKWZRmbszU',
    appId: '1:887208119857:web:6127d3170025adc9134f10',
    messagingSenderId: '887208119857',
    projectId: 'umai-app',
    authDomain: 'umai-app.firebaseapp.com',
    storageBucket: 'umai-app.appspot.com',
    measurementId: 'G-3108K4VG9F',
  );
}
